[package]
name = "jv_support"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = []
profiling = []

[dependencies]
once_cell = "1.20"
toml = "0.8"
bumpalo = "3.14"
serde = { workspace = true, features = ["derive"] }
