[package]
name = "jv_parser_syntax"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
chumsky.workspace = true
jv_lexer.workspace = true
jv_ast.workspace = true
jv_parser_semantics.workspace = true
thiserror.workspace = true

[lib]
crate-type = ["rlib"]
