[package]
name = "jv_inference"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Hindley-Milner type inference engine for the jv language"

[dependencies]
jv_ast = { workspace = true }
