# Emergency chumsky SIGKILL fix configuration
# Ultra-aggressive optimization disabling

[build]
rustflags = [
    "-C", "opt-level=0",
    "-C", "debuginfo=0",
    "-C", "codegen-units=1",
    "-C", "incremental=false",
    "-C", "target-cpu=generic"
]

[profile.dev]
opt-level = 0
debug = false
lto = false
codegen-units = 1
incremental = false

[profile.test]
opt-level = 0
debug = false
lto = false
codegen-units = 1
incremental = false

# Disable all target-specific optimizations
[target.'cfg(all())']
rustflags = [
    "-C", "opt-level=0",
    "-C", "debuginfo=0",
    "-C", "codegen-units=1",
    "-C", "target-cpu=generic"
]

[env]
CARGO_INCREMENTAL = "0"
RUST_BACKTRACE = "0"

# Sparse registry for efficiency
[registries.crates-io]
protocol = "sparse"