[package]
name = "jv_docs"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
jv_parser_frontend = { path = "../jv_parser_frontend" }
jv_parser_rowan = { path = "../jv_parser_rowan" }
